### ISSUE TITLE
How will farmer's authenticity be verified?

### ISSUE THREAD

**Issue by VandittSama** [SJSUFall2019-CMPE272/AgriFund#2]
I agree that the identity of a farmer should be verified before giving him the benefits of donation since  one of the aims of the project is to make sure that funds go to appropriate beneficiaries. But the question is, what methodology/technology are you planning to use to ensure that only legitimate farmers are able to register and receive funds? Physically visiting each and every farmer in a country is not a viable solution, more so for a project based out of California. How will you avoid the misuse of this application by people who try to register as fake farmers?

**Comment by dhanasreeA** [comment]
There's a lot of ways to identify actual farmers. Some options are the Aadhaar card, Pattadhar passbook, certain portal/certificates like small farmers certificate, etc. 

Ref:
https://farmer.gov.in/aboutus.aspx
https://www.youtube.com/watch?v=KpHkUIO4W-U
https://www.indiafilings.com/learn/small-farmer-certificate/
