### ISSUE TITLE
Blockchain issues

### ISSUE THREAD

**Issue by jojojoseph94** [SJSUFall2019-CMPE272/AgriFund#3]
There are some issues/doubts with using blockchain in the design
1. How will you convert real money to blockchain? Are you going to use a cryptocurrency which can be purchased by the users?
2. Most cryptocurrency transactions are banned in India. How do you plan to overcome that?
3. If there is a human error in any of the transactions can it be reversed in such a system?
4. How will the farmers use the funds received via blockchain? Will there be an exchange to convert it back to real cash?

**Comment by dhanasreeA** [comment]
It's a common misconception that blockchain is synonymously used with just cryptocurrency. In our project, the transactions will take place using regular banking services for now. What the blockchain maintains is, a clear, transparent and non-editable record of these transactions that is accessible by all parties engaged in the system.
