### ISSUE TITLE
Issue of App usage by farmers

### ISSUE THREAD

**Issue by shivangi-jain** [SJSUFall2019-CMPE272/AgriFund#6]
Only 30 million out of 120 million farmers in India use Smartphones (source: Forbes,Suparna Dutt D'Cunha). Also, we are not sure if they are capable of listing their problems and using the app since the literacy rate in agriculture dominant areas like Uttar Pradesh, Bihar is pretty low.  Also, there are network connectivity issues still prevalent in small towns in India which can hamper the usage of this app. Are these issues being considered and how can they be addressed?

**Comment by dhanasreeA** [comment]
With the government of India's Digital India initiative, It won't be long before every farmer has access to the internet. Government is trying to bring farmers closer to technology - Jharkhand's government announced that they will give away free mobile phones to farmers.
While the government is coming up with virtual marketplaces it should not be difficult for the farmers to be able to use a basic user friendly website.
